// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZmFmGUzeJMqTmatgSAbxMF1k-v2gXvU',
    appId: '1:981446746948:web:4748a1eec60e370404ad11',
    messagingSenderId: '981446746948',
    projectId: 'project-1-8bd7e',
    authDomain: 'project-1-8bd7e.firebaseapp.com',
    storageBucket: 'project-1-8bd7e.firebasestorage.app',
    measurementId: 'G-L10WKNXNP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSf6FdGrhHgKJxleC_FLrxRDLGUFxPk5o',
    appId: '1:981446746948:android:b0f19fd2040076c204ad11',
    messagingSenderId: '981446746948',
    projectId: 'project-1-8bd7e',
    storageBucket: 'project-1-8bd7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj3tYm_g-TtOFuMVcZIPmt2D2vvcWi2Eo',
    appId: '1:981446746948:ios:373df80e40d785e204ad11',
    messagingSenderId: '981446746948',
    projectId: 'project-1-8bd7e',
    storageBucket: 'project-1-8bd7e.firebasestorage.app',
    iosClientId: '981446746948-1ht9711qgl677htijmufkd58s5psqg78.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj3tYm_g-TtOFuMVcZIPmt2D2vvcWi2Eo',
    appId: '1:981446746948:ios:373df80e40d785e204ad11',
    messagingSenderId: '981446746948',
    projectId: 'project-1-8bd7e',
    storageBucket: 'project-1-8bd7e.firebasestorage.app',
    iosClientId: '981446746948-1ht9711qgl677htijmufkd58s5psqg78.apps.googleusercontent.com',
    iosBundleId: 'com.example.safeSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZmFmGUzeJMqTmatgSAbxMF1k-v2gXvU',
    appId: '1:981446746948:web:0df280df8250beed04ad11',
    messagingSenderId: '981446746948',
    projectId: 'project-1-8bd7e',
    authDomain: 'project-1-8bd7e.firebaseapp.com',
    storageBucket: 'project-1-8bd7e.firebasestorage.app',
    measurementId: 'G-H0GTRXLMEY',
  );
}
